### ISSUE TITLE
Remove href attribute from empty URL field links in the metadata list

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#101]

**Comment by tnajdek** [comment]
Not sure if this is still applicable. There won't be `href` attribute if the field is truly empty. However if it has a value of " " (space) or similar, it will include `href=" "`. Perhaps we should validate the url?

**Comment by flachware** [comment]
I think it is not applicable anymore. However, being able to input a space is a layout problem: when there is a space inside the input isn’t empty anymore and thus CSS does not insert a non breaking space – which is needed to stretch the editable to the correct height. It would be great if we could avoid that.

Also, when I enter a space and try to change it to something else later, I get the error below.

![screen shot 2018-08-04 at 16 33 03](https://user-images.githubusercontent.com/419747/43677584-728bcf42-9804-11e8-9954-17d991504fee.png)

**Comment by tnajdek** [comment]
The original issue has been resolved because we're testing if the URL actually looks like URL before displaying a link.

The latter issue is caused by two factors. First we didn't trim the value locally so we would display an empty space causing layout problem, this has been fixed. Secondly sending unchanged input increments version triggering an error and a library reset upon further edit, this is tracked as zotero/dataserver#81
