### ISSUE TITLE
Editable busy state

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#115]
Show spinner next to `.editable-content` instead of `.editable-control` in busy state.

**Comment by tnajdek** [comment]
This would cause spinner to never render in "form mode" (which we use in on devices where there is explicit Edit button).

Currently `Input` component contains `isBusy` prop which renders a spinner inside input-group, next to `form-control` or `editable-control` depending on which mode you're in. At this stage `.editable-content` doesn't even exist because `Editable` component is active showing inputs, instead of content. Furthermore `Editable` component is skipped entirely in `Form` mode. Hence this change would:

1. Require substantial change so that `Editable` is inactive during update period
2. As mentioned at the top, would prevent spinner from being rendered in "form mode" entirely.

I'm looking to simplify `ItemBox`, this would pile up another level of complexity. Can we somehow get around this or come up with something more universal across all the variants of the `ItemBox` component?

**Comment by flachware** [comment]
If I understand correctly the spinner is tied to the `Input` component. Unless we can have a second spinner in the `Editable` that gets displayed instead the one of the `Input` spinner, I think we have to work with the one we have.

So, for the sake of simplicity, I’ll tweak the current spinner (at least I found a way to sub-pixel size/align it).
