### ISSUE TITLE
Feature: Generate bibliography

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#134]
I believe ideally this would show in a popup that can be opened whenever one or more items are selected. It would offer functionality similar to ZoteroBib i.e. a style selector with option to install additional styles, a container with bibliography rendered in current style in html and a button offering "copy to clipboard" with additional options (Download RTF, Copy HTML) hidden in a dropdown.

Any thoughts or comments?

(Related to #113)

**Comment by stakats** [comment]
I think that sounds fine. I like ZoteroBib's interface here. Would we similarly store "active" styles in local storage?

**Comment by tnajdek** [comment]
One thing we need to figure out is how to implement style installer - I don't think it can open a new modal, because bibliography interface itself is already in a modal.

**Comment by flachware** [comment]
<img width="1536" alt="bibliography-desktop 2x" src="https://user-images.githubusercontent.com/419747/53180904-d13a5a00-35f6-11e9-8b51-8d18de7c3688.png">
<img width="320" alt="bibliography-mobile 2x" src="https://user-images.githubusercontent.com/419747/53180916-d7c8d180-35f6-11e9-9066-e157f0d8d574.png">

('9,300+ other styles available…' entry in style selector – like on zbib.org)

**Comment by dstillman** [comment]
I would leave the split-button with "Copy HTML" in a menu. We could conceivably have other options later (e.g., "Print"), and "Copy HTML" is an advanced option that most people won't need to use (but when presented at the same time is somewhat confusing).

**Comment by flachware** [comment]
I mainly tried to avoid a single-option menu. In order to mitigate the confusion I made 'Copy to Clipboard' a stronger button than 'Copy HTML'. But if the single-option is fine, let’s go with the split button.

<img width="1536" alt="bibliography-desktop 2x" src="https://user-images.githubusercontent.com/419747/53234181-42c5e700-368f-11e9-83c8-0e7df1e87129.png">

**Comment by flachware** [comment]
@tnajdek could you enhance the StyleSelector and LocaleSelector component so they can be passed an ID? We would need that to link the labels.

Related, I converted CheckboxSet into RadioSet and restructured it to use explicit labels (using `for` instead of nesting the input in the label) as it is the recommended way by the W3C for accessibility reasons (Bootstrap switched to explicit labels too). We would need to be able to pass an ID to the RadioSet too (that gets used in `for` and `id` attributes inside the component.

**Comment by flachware** [comment]
@tnajdek the react selects have a different id than the native selects. And if I’m not mistaken even with matching ids they would not get into the `is-focused` state currently when you click the label?

**Comment by tnajdek** [comment]
@flachware I've tweaked `<Select>` inputs in the bibliography modal to be searchable. This way an actual input field is rendered and for/id works much better, in line with how it behaves in the item box.

**Comment by flachware** [comment]
@tnajdek I wasn’t aware that non-searchable react-selects aren’t capable of for/id focus by default. It isn’t a real usability issue, in macOS you can’t click the label to focus inputs or selects neither (it’s a different thing for checkboxes). So I think it’s a convenience feature only and we should set the `searchable` option depending on wether or not there are lots of options.

**Comment by flachware** [comment]
@tnajdek I just noticed that the copy-to-clipboard button can’t be triggered via enter key when it has the focus. Same on zbib.org – is there a reason for that?

**Comment by flachware** [comment]
@tnajdek you might have missed this question in the channel: could we remove the wrapping div in style-selector and template-selector and set the class instead directly on the Select component (so it gets set on the input-group)?

**Comment by flachware** [comment]
@tnajdek I’m closing this issue in favor of #213.
