### ISSUE TITLE
Updating an item in a trash, undeletes it, doesn't refresh

### ISSUE THREAD

**Issue by stakats** [zotero/web-library#154]
This may be related to other refresh issues, but on dragging an item out of the trash, that item still appears in the trash unless I reload the page entirely.

**Comment by tnajdek** [comment]
Thanks, it seems updating an item in the trash is generally not working as expected. Will investigate further.

**Comment by tnajdek** [comment]
This was a multi-layer bug. Firstly, when dragging item from a trash to a collection, it shouldn't be untrashed, this has been fixed in zotero/dataserver@065760efc8c944bdf20f4518f8767bed4f56a94f

Secondly, web-library didn't handle adding items from trash to a collection very well, this has been fixed in the above commit.

This is now expected to behave as it does in the client (i.e. item itself is changed behind the scenes, but it only appears in the collection when explicitly untrashed)
