### ISSUE TITLE
Scroll to selected item

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#172]
- [x] When the url contains specific item or items (scroll to first item in the latter case)
- [x] When creating a new item in current collection/library

**Comment by dstillman** [comment]
FWIW, here's what we do in the client:

https://github.com/zotero/zotero/blob/db56f002a533224a761d6e409fab39f8d05e8dbe/chrome/content/zotero/xpcom/itemTreeView.js#L1948-L1966

When scrolling down, we try to scroll 5 rows past the target, since having the selected row all the way at the bottom isn't that nice.

When scrolling up, we only scroll to the specified row or, if it's a child item and we have room, its parent. I think I felt that viewing the row (or its parent) as the top row was fine and scrolling past it felt a little odd.
