### ISSUE TITLE
Decrease mobile text size

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#176]
I haven't tried current versions on mobile, but if [these screenshots](https://github.com/zotero/web-library/issues/150#issuecomment-461445858) are accurate and the scaling is the same, the text size is far larger than the default text size on iOS. Compare to Mail:

<img src="https://user-images.githubusercontent.com/419747/52416844-d96ca280-2aea-11e9-89fe-21650467f2d1.png" width="400">

<img src="https://user-images.githubusercontent.com/783082/52523233-f8327c80-2c43-11e9-8386-48e8d194f458.PNG" width="400">

The row height is also a little bigger. Together, this just gives us much lower information density than we could have.

**Comment by flachware** [comment]
The comparison is not accurate because the scaling is not the same (different viewport widths). Below please find the real situation. The default text size in iOS is 17px, we use 16px in the web-library on touch devices – so we already have a comparable information density in terms of the font size. I’ll have a look at the items-list row height when I address #177.

<img width="320" alt="web-library" src="https://user-images.githubusercontent.com/419747/52564935-afc2bc80-2e05-11e9-83b1-9c2e2f8542e0.png">
<img width="320" alt="apple-mail" src="https://user-images.githubusercontent.com/419747/52564920-a3d6fa80-2e05-11e9-834c-c1958a8a72a7.png">

**Comment by flachware** [comment]
I think that’s clarified, closing.
