### ISSUE TITLE
Add placeholder class and text to untitled items

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#190]
@tnajdek could you set a `.placeholder` class on `.item-title` and add the text `Untitled` inside the element when it’s empty (info pane in default mode)?

**Comment by flachware** [comment]
Looks good to me, thanks!

**Comment by stakats** [comment]
Untitled items are not showing as "Untitled" in either the info pane or the items pane.

**Comment by tnajdek** [comment]
Just to clarify, we want all of the following:

* A placeholder "Untitled" in an input in item details in all variants (editable on/off) unless any actual value is entered
* All items with title field empty, to say "untitled" in items table (desktop) and items list (touch/small). Should this be slightly grayed out?

Just making sure because this is not what we do in the client where we just leave no-value fields empty (as currently implemented in web-library).

**Comment by flachware** [comment]
This issue was just about touch devices originally, and it still works as expected there. There was a pragmatic reason to add a placeholder on touch devices (in default mode only) to make the layout work.

But I doubt we want placeholders in the desktop version? I think it is a good thing to have empty gaps wherever some information is missing, it gives you a stronger hint about the absence of metadata.

**Comment by dstillman** [comment]
Yeah, I'm not sure why we'd have "Untitled" on desktop where we don't in the client.

**Comment by tnajdek** [comment]
I'm going to assume we're happy with not having "Untitled" here and no changes required. 

@stakats @dstillman @flachware Please feel free to reopen if you think we should do otherwise.
