### ISSUE TITLE
Notes summaries should handle line breaks and whitespace better

### ISSUE THREAD

**Issue by stakats** [zotero/web-library#199]
I have a note that appears summarized like this in web-library:

>Médecine des Chinois, 2:466-477&amp;nbsp;ginsengteaelephant flesh, skin, ivorycamel flesh and fatseahorse&amp;nbsp;closes with forensic medicine...

but instead it could look like this:

>Médecine des Chinois, 2:466-477¶ ginseng¶ tea¶ elephant flesh, skin, ivory¶ camel flesh and fat¶ seahorse¶ closes with forensic medicine...

Or we could just only show the first line, like we do in the desktop version.

**Comment by flachware** [comment]
I would suggest to try to make them 2 lines (needs js truncation) and concatenate everything with a simple whitespace:

> Médecine des Chinois, 2:466-477 ginseng tea elephant flesh, skin, ivory camel flesh and fat seahorse closes with forensic medicine...

**Comment by tnajdek** [comment]
I've improved this, pretty much like @flachware suggested. Note summaries should no longer contain any untreated special entities (e.g. `&nbsp`) and we generate summary from the first 180 chars, instead of using only the first line. Finally new lines and `<br />` should always produce a single whitespace.

Hope this works, please feel free to re-open for any further tweaks.

**Comment by flachware** [comment]
@tnajdek looks good to me.
