### ISSUE TITLE
Copy-to-clipboard button can’t be triggered with enter key

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#213]
> @tnajdek I just noticed that the copy-to-clipboard button can’t be triggered via enter key when it has the focus. Same on zbib.org – is there a reason for that?

**Comment by tnajdek** [comment]
@flachware normally there is no need to handle keydowns explicitly on buttons, because browser will trigger a synthetic click event on relevant key presses (https://www.w3.org/TR/html5/single-page.html#activation ). However in this particular scenario `<Dropdown>` contains `keydown` handler that calls `preventDefault`, thus the synthetic event is not triggered.

I've fixed it by handling relevant keydown events as well as click. Similar fix will be needed on zbib.org.
