### ISSUE TITLE
Creator column is updated on reload only

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#217]
When you edit the creator (author, etc.) in the info pane you need to reload to see the new value in the items table.

**Comment by tnajdek** [comment]
This is because we're depending on API to provide this piece of data via meta, however that's not possible when doing PATCH update. Instead we need to re-implement some logic from the API in web-library:

https://github.com/zotero/dataserver/blob/88032c80feda28229402ea7173b4d201513bbef0/model/Item.inc.php#L788

https://github.com/zotero/dataserver/blob/0c1bce50ba6ed22f05bc4f85ec788c6188d700d0/model/Date.inc.php#L330

**Comment by dstillman** [comment]
Do you mean a literal `PATCH`? Because you can just use `POST`, which follows `PATCH` semantics, and get back the saved object. (In the next API version we'll probably fix `PUT`/`POST` to return 200 + JSON instead of 204.

**Comment by tnajdek** [comment]
Thanks @dstillman. I've opted to do POST on the plural endpoint whenever updating 'creators' or 'date' instead of re-implementing that logic.
