### ISSUE TITLE
Item view actions

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#224]
In the client, double-clicking an item either opens the best available attachment (with some logic to choose the best PDF or snapshot among available options) or views the item online using the URL or DOI. Do we have an equivalent here?

Is this waiting on https://github.com/zotero/dataserver/issues/87? If so, how do we see the UI working?

(I know we have the URL or DOI labels in the right-hand pane, which address the latter if you know about them.)

**Comment by flachware** [comment]
The View PDF / View Online actions are not only bound to double-click (I didn’t realize that you can double click items in the client!) but also to corresponding context menu options. As we generally provide an icon in the toolbar for context menu options my first idea would be a 'view' icon in the toolbar.

**Comment by tnajdek** [comment]
Double-click to open best attachment is done in #268.

I've introduced "View File" / "View Online" options to the "..." menu in the toolbar. If API provides `attachment` it will display "View File/PDF". Otherwise it will display "View Online" if URL or DOI is present & valid. Ideally we would also display "View Online" if first attachment is a valid link, but since we may not have child items fetched at this state, this doesn't happen here (it still happens for double click).
