### ISSUE TITLE
gh pages hosting?

### ISSUE THREAD

**Issue by nafergo** [zotero/web-library#237]
Is it possible to host this on github pages? Any examples?

**Comment by nafergo** [comment]
I probably should explain a little better: I want to publish a website that pulls a group library from zotero. The group can edit/add refs on zotero and the website will be a public and more friendly view of the group references. And I am looking to host it on github pages... I would be extremely grateful for any ideas and suggestions.

**Comment by tnajdek** [comment]
Please use [Zotero Forums](https://forums.zotero.org/) for any support queries, bug reports and feature requests.

Since web library has no server component it should be possible to host it on Github pages. You'd need to setup configuration (see `src/index.html` for example) and customize the app as you see fit.
