### ISSUE TITLE
Remove field focus while saving

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#240]
1. Click in a field and change its value.
2. Tab to the next field.

Until the save finishes, both fields appear to have focus. Only one field should show as focused at once.

**Comment by flachware** [comment]
@tnajdek if I’m not mistaken this is related to #115.

I think there is an easy way out: we already have the `busy` class, so I could style the busy editable to look like an inactive editable – plus the existing spinner.

Does anything speak against that? I would actually welcome this change, because that’s the look I wanted to achieve for the busy state in the first place.

**Comment by tnajdek** [comment]
Sounds good to me.

**Comment by flachware** [comment]
@tnajdek I’ve got a weird issue: When there is text with overflow in an input editable and you leave the editable with tab everything works as expected. But when you hit enter instead, the ellipsis is missing. How do tab and enter differ in terms of blurring an editable?

**Comment by tnajdek** [comment]
> I’ve got a weird issue: When there is text with overflow in an input editable and you leave the editable with tab everything works as expected. But when you hit enter instead, the ellipsis is missing. How do tab and enter differ in terms of blurring an editable?

As far as I can tell we're rendering identical HTML in both cases so I suspect some browser optimization is at play here. For such a tiny glitch I don't think it makes sense spending any more time investigating at this point, we can revisit post 1.0.

Other than that, can we close this issue?
