### ISSUE TITLE
Tags pane (desktops)

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#247]
- [x] Add autocomplete

**Comment by flachware** [comment]
@tnajdek could we add an autocomplete to the tag editables while editing?

**Comment by tnajdek** [comment]
@flachware it would need to be network-backed as we won't have all the tags downloaded locally and AFAIK there is no API support for tag search by partial name so it would require API changes.

CC @dstillman

**Comment by flachware** [comment]
@tnajdek there some issues I would need your help with:

- when a tag with an assigned color is being added the SVG symbol has to be set to `circle` and the color has to be set like we do it in the items table (assuming that we can show tag colors in the tags pane).
- Would it be possible to create a new virtual tag as soon as you enter a tag (so you can easily add multiple tags in a row)?
- Currently, when a you add a duplicate tag the editable goes into busy state and then the tag would disappear. Would it be possible to just clear the editable (like in the client) so you can continue typing without the need to create a virtual tag first?

**Comment by dstillman** [comment]
> it would need to be network-backed as we won't have all the tags downloaded locally and AFAIK there is no API support for tag search by partial name so it would require API changes.

Partial tag search is possible with `…/tags?q=foo`. It's currently case-sensitive, though we should fix that. Not sure how it performs in a large library. (It's not left-bound, unlike tag search in the client, but we could add a way to make it so.)

**Comment by tnajdek** [comment]
If we could do `…/tags?q=foo&qmode=startswith` (or something like that) that would be ideal, auto-complete could make a request limited to say 10 results which would be offered as completion suggestions.

Otherwise we would need to do  `…/tags?q=foo` and discard results that match but do not start with string entered. In this scenario we cannot limit results to just 10 because we don't know how many results will need to be discarded. 

The latter case is inefficient so if we decide to do that, I'd say we should only auto-suggest once 2 or 3 characters have been entered in the input. The former case is much nicer but needs api changes.

**Comment by dstillman** [comment]
> …/tags?q=foo&qmode=startswith

That should work.

**Comment by dstillman** [comment]
I've implemented `qmode=startswith` on apidev.

**Comment by flachware** [comment]
@tnajdek I believe adding a new tag used to work a bit different – could you not render the 'remove' button for new/virtual items?

**Comment by tnajdek** [comment]
@dstillman thanks for implementing `qmode=startswith`, this works great! I didn't realize this before but tag completion should probably be case-insensitive, any chances for something like a switch to toggle case sensitivity?
