### ISSUE TITLE
Related pane (desktops)

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#249]

**Comment by flachware** [comment]
@tnajdek there are some issues in the related pane:

- [ ] Could you set the loading class on `.tab-pane` while the related items are being fetched (like in the attachment pane?

- [ ] Could you replace the document icon with the item type icons that we use in the items-table?

- [ ] I think we have to improve the behavior once you click a related item in the list. the related item in the items-table gets selected, but it is very likely to be out of sight. Could we scroll to the item that gets selected when you choose it in the related pane?

**Comment by tnajdek** [comment]
> Could we scroll to the item that gets selected when you choose it in the related pane?

Scrolling is tricky because we might might not have the entire set downloaded hence we don't know where given item would appear in the list. However we've a best-effort implementation in place where newly-selected item is scrolled to if already present in the list. I hope to revisit this and come up with better implementation in the future, probably post 1.0 release tho.

**Comment by flachware** [comment]
I’ve figured that this would be tricky. Just to clarify, with scrolling I do not mean an animated scroll, just a hard jump to that item.

I guess the more common use case would be that I select an item and send the URL to somebody. When that person opens the link the item would ideally be selected and the first item in the table. Otherwise you would have to scroll arbitrarily as long as the item has been loaded.

**Comment by tnajdek** [comment]
Both cases are affected by the same issue, tracked here: #253

**Comment by flachware** [comment]
Alright. I think this issue is good to close otherwise?
