### ISSUE TITLE
Tag selector (desktops)

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#250]
<img width="1216" alt="tag-selector@2x" src="https://user-images.githubusercontent.com/419747/62967035-80b6f300-be08-11e9-809a-5c3202ee38f7.png">

**Comment by stakats** [comment]
Nice.

**Comment by flachware** [comment]
@dstillman @tnajdek @stakats above please find a mockup of the tag selector UI:

1) By default the tag selector would be minimized. You can toggle the tag selector by clicking on the 'Tags' header. As we don’t have resizable layout components (except for the table columns) the tag selector would not be resizable for now. Apart from this I think toggling is faster and more convenient than resizing here.

2) Once you clicked on the tag selector it would maximize (e.g. half of the sidebar) and focus the filter box. Of course you don’t have to filter, you can also just scroll and pick a tag.

3) Typing in the search box shows a clear button and filters down the list.

4) Once you have picked a tag it shows up on top of the list and it gets a remove button. The cleared filter box gets the focus again. Note that selected tags do not scroll away (I’ve added a scrollbar to demonstrate this).

This works basically like a permanent multi select, it solves the shortcoming of the current tag selector, where you don’t have an overview of the currently selected tags.

**Comment by tnajdek** [comment]
This solution has one more advantage: with each tag being one row, we can easily do virtualisation of the tag list which should offer better experience when scrolling a large list - it would behave similarly to items list with placeholders. This would replace current preemptive fetching when scrolling mechanism.

Another advantage is: I can see this working in a very similar way on touch and small devices.

Main disadvantage is that you don't immediately see what tags are selected. It's entirely possible to arrive at a pre-filtered library via url. I assume when you collapse tag selector with some tags selected it says "2 tags selected" instead of "Tags" on the drop-down (pull-up?) button. We should probably make it stand-out so it's not confusing.

Another disadvantage is that it's significantly different from the client behaviour, not sure how important that is.

Also we're missing some functionality that, while currently not implemented in web-library, we will probably need to add in future: "Deselect all", "Show automatic tags", "Display all tags in this library".

All in all I like this solution slightly more than the current one but would like to make sure everyone's happy with it before we start implementation.

**Comment by dstillman** [comment]
As Tom says, this significantly changes the way this works from the client, and I'm concerned it's mostly not for the better.

> By default the tag selector would be minimized.

Why? The tag selector is a main part of finding items in Zotero. Why would we hide it by default in the desktop layout when we have plenty of room?

The tag selector exists primarily to 1) show you the tags associated with the current items and 2) quickly click them with the mouse. Both of those are compromised by the lower density and by putting the filter bar at the top. With up to 9 colored tags, you'd often only see a few more non-colored tags in this version. Adding the filter box to the top seems unnecessarily distracting from the tags themselves for something that often isn't necessary to use — it's often faster to just click on the tags within view or quickly scroll through a short list without needing to switch to the keyboard to filter before going back to the mouse. The lower density makes filtering somewhat more necessary, but that's a problem created by the lower density. In the client, it's pretty easy to ignore the filter box when you don't need it.

> Once you have picked a tag it shows up on top of the list and it gets a remove button.

This would be somewhat confusing with the colored tags that already appear at the top, and it would push other tags you may want to click further down — possibly out of view, if you have a bunch of colored tags (which always appear, since another function of the tag selector is to provide a way to quickly assign tags to items by dragging).

> This works basically like a permanent multi select, it solves the shortcoming of the current tag selector, where you don’t have an overview of the currently selected tags.

It's not much of a shortcoming. In the default mode, where clicking a tag filters by items with that tag (i.e., with "Display all tags in this library" off), it generally filters down very fast, so — at least at the client density — it's pretty rare to end up with much more than one screen of tags once you've selected one of them.

> This solution has one more advantage: with each tag being one row, we can easily do virtualisation of the tag list which should offer better experience when scrolling a large list

That's true. We do virtualize the client tag selector, but we can only do that with the inline layout because we have all tags loaded ahead of time and can calculate their widths. It seems like here with the inline view it would need to be infinite scrolling instead of fixed scrolling if we wanted to virtualize, which would be a little more clumsy. But we also wouldn't need to virtualize below a fairly large number of tags.

I agree that this might work better on touch devices, where you need large tap targets, typing might be faster, and/or you can use an iOS-style letter-based sidebar scroll thing to quickly jump to a particular part of the alphabet.

**Comment by flachware** [comment]
>Why would we hide it by default in the desktop layout when we have plenty of room?

Because we do not have plenty of room. The collection tree easily fills the entire sidebar and so do the tags. But you don’t need both at the same time permanently. Having a permanent split view in the sidebar means more scrolling in both splits and it feels cramped. So I’d suggest a solution that prioritizes either the work with collections or the work with tags and try to maximize the prioritized area.

I think it is totally not worth having a not nice/denser/chaotic layout in the sidebar if it is only a partial solution to the problem of quantity. Your Zotero library can be a lifelong project, you can end up with hundreds, even thousands of tags. In this case only the filter box is an adequate solution, you can’t fix this with a denser layout and scrolling.

Showing the filter box at the bottom of the tag list is less distracting, but also less logical. I think it is more common to have a filter above the elements you are going to filter than below. I also think there are some options to mute the filter box in case it is unused and unmute it on hover/focus.

>It's not much of a shortcoming.

That’s true. When 'display all tags in this library' is off it is very unlikely that you end up with a long list once you have selected the first tag, hence there is probably no need to sort selected tags to the top.

**Comment by dstillman** [comment]
> Because we do not have plenty of room.

I mean, we have nearly as much room as there's always been in most standalone Zotero windows, and far more than we had in Zotero for Firefox when we originated the split-pane layout. And judging by screenshots we see, most people leave the tag selector open.

> So I’d suggest a solution that prioritizes either the work with collections or the work with tags and try to maximize the prioritized area.

But they're not mutually exclusive. In standard use of Zotero, you'd be very likely to click on a collection, look at the then-much-shorter list of tags, and click one to further filter the list. What you've mocked up is quite nice for a tag interface that gets pulled up occasionally and then closed, but that's not how the tag selector (which is also used for assigning tags) is meant to be used.

You've always been able to close the tag selector in Zotero in case you're, say, doing some heavy collections work, but we'd never hide it by default.

> Your Zotero library can be a lifelong project, you can end up with hundreds, even thousands of tags. In this case only the filter box is an adequate solution, you can’t fix this with a denser layout and scrolling.
And that's why the filter box exists in the client, but it's still mostly only necessary in the library root. In many collections, the tags would fit within view or within a couple scroll pages in the client's tag selector.

> I think it is more common to have a filter above the elements you are going to filter than below.

For sure, but I don't think that's a good enough reason to make it more prominent when doing so would make the actual content harder to view and when in most non-library-root cases using it would be slower than just scrolling and clicking. (The Firefox/Thunderbird content search bar is a prominent example of a search bar at the bottom.)

(And again, this is just on desktop, where people will expect to work the same way they do in the client. I have no problem with diverging more for touch.)

**Comment by flachware** [comment]
<img width="1216" alt="tag-selector-2@2x" src="https://user-images.githubusercontent.com/419747/63046339-81b45700-bed2-11e9-939f-0f70e18118a0.png">

Ok, this would be the current approach. We could mute the tags a bit to give the eyes some relief – and unmute them on hover/focus/selected tag. As Tom suggested we could update the header and show the number of selected items, but I think we should disallow collapsing the tag selector when there are selected tags altogether?

**Comment by dstillman** [comment]
I don't think we need the "Tags" header taking up space, at least on desktop. When there are no tags (e.g., in an empty library), it should say "No tags to display" in the middle, and after that people know what this thing is for. We should just use the space to actually display tags (which also means using something else to collapse the pane).

The muting also won't work, I'm afraid. When using "Display all tags in this library", tags that don't match the current results get shown in gray, while matching tags are black. And regardless of that setting, colored tags (which always appear in all views) are shown with less opacity when they don't match any visible items. I don't think seeing the number of selected tags matters too much — as we said above, when one is selected it's quite likely to be in view. It also resets when you switch collections, so it's not like you would get stuck with tags on.

> As Tom suggested we could update the header and show the number of selected items, but I think we should disallow collapsing the tag selector when there are selected tags altogether?

I think we should just deselect all tags when closing the tag selector. They get deselected when you switch collections anyway, so if you're closing it to get a better view of your collections it's about to become irrelevant anyway. I'll make this change in the client too.

**Comment by flachware** [comment]
>I don't think we need the "Tags" header taking up space, at least on desktop.

'All Tags' plus the chevron have two purposes: all sections in the sidebar have a heading (My Library is an exception) and we need something to click on to toggle the tag selector. What else would you use to facilitate collapse/expand when there is only the top border left?

**Comment by dstillman** [comment]
> What else would you use to facilitate collapse/expand when there is only the top border left?

A grippy in the splitter, as in the client. Most people won't be opening and closing this regularly, so this doesn't need to eat into the far more important real estate for actually displaying tags.

**Comment by flachware** [comment]
@tnajdek what is the `.tag.placeholder` state for, is it still in use? Do placeholders work like in the items table/list, like, they are empty while they have the class and once the string is inserted the placeholder class gets removed?

**Comment by tnajdek** [comment]
> @tnajdek what is the .tag.placeholder state for, is it still in use

No, this must be left-over from previous experiments with virtual scrolling, please remove.

**Comment by flachware** [comment]
Ok.

**Comment by flachware** [comment]
@tnajdek is this good to close?
