### ISSUE TITLE
Redirect all canonical URLs to web-library URLs

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#259]
https://groups.google.com/d/msg/zotero-dev/wryVEd_mJNM/pL5_Do48AgAJ

E.g., `/groups/:groupID/collections/:collectionKey/items/:itemKey` to…whatever the web library uses to select an item within a collection. The same for all the major API-equivalent URLs. This will let us add support for opening collections and items on the web from the client.

(We could do these in PHP (and maybe are? I didn't check), but I assume the web library is getting all URLs under a few top-level paths? And this should probably work with other installs as well. And there's no real need for proper HTTP redirects when the end result is a SPA anyway.)

**Comment by tnajdek** [comment]
This mostly works already, we have some redirects server-side that take care of redirecting `/user/:userID` and `/groups/:groupID` to web-library equivalent (with slugs) and `collections/:collectionID` and `items/:itemID` (these are redirected to old web library url scheme but that's handled in web-library routes to redirect to a new scheme). By bit of a coincedence`items/trash` and `items/publications` also work though this could be handled better.

Are there any other major API-equivalent URLs that should be redirected?

> there's no real need for proper HTTP redirects when the end result is a SPA anyway.

Some of the canonical-to-web-library redirects lead to pages that are not handled by a SPA web-library, e.g. `/users/:userID` redirects to `/:userslug` i.e. user profile. I think it makes more sense to keep these consistent, instead of trying to handle more inside the SPA. That being said, redirects are currently 302, I think 301 would be more appropriate in this case?

**Comment by dstillman** [comment]
> Are there any other major API-equivalent URLs that should be redirected?

One I noticed was item-within-a-collection — e.g., `/users/:userID/collections/:collectionID/items/:itemID`.

I didn't test whether child note/attachment URLs work, but I'd guess not. Could probably just focus the right tab pane there, if we're not currently.

> That being said, redirects are currently 302, I think 301 would be more appropriate in this case?

I don't think so. Since the canonical URL is, well, canonical, returning a 302 from there to a less-canonical URL makes sense to me. And, actually, the username, for example, could change, so a 302 is appropriate.

**Comment by tnajdek** [comment]
> I didn't test whether child note/attachment URLs work, but I'd guess not. Could probably just focus the right tab pane there, if we're not currently.

Not sure if we can make this work like that because canonical URL for child item does not include parent item key. Thus we would need to treat this as a special case, fetch the child item, check parent and only then do the redirect.

What we currently do instead currently is display the item as if it was a stand-alone item in the item details pane. It's possible to edit the note or download the attachment from that view. No item is highlighted in items list because child items do not appear in this list.

I think this best-effort support is sufficient for 1.0 but please let me know if you believe otherwise.

Other than that I think this is done.
