### ISSUE TITLE
Tags and attachments in read-only libraries

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#308]
Currently, tags and attachments can be added to read-only libraries (at least the Add buttons are not disabled). Is this on purpose?

**Comment by tnajdek** [comment]
No that's a bug, buttons should be disabled.

**Comment by dstillman** [comment]
In the client we don't show the buttons at all in read-only libraries. Particularly in the web library, if you're just viewing someone else's library, it seems sort of inappropriate to show UI elements meant for editing. (We could take that further by not showing certain toolbar buttons.)

There could in theory be a difference here between viewing a read-only library and being in a read-only view within a library that's otherwise editable. In the latter case, disabled buttons would make a bit more sense.

**Comment by flachware** [comment]
I agree that we should not insert the buttons at all in read-only libraries if there is no case in which they are operational.
