### ISSUE TITLE
Column dragging weirdness

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#382]
1. If I try to drag a column to the right-most position, the blue drop target doesn't appear to the right of the right-most column, even though there's a border line there. If I let go there, the drop mode stays activated and the blue drop targets appear as I move the mouse across the column headers, even though I'm not holding down the mouse button. If I then click, the column moves.

2. The drop target behavior doesn't seem right in general. If I have columns A, B, and C, and I click and hold on B and drag the mouse slightly to the right, the right border between B and C is highlighted in blue, and if I let go the column moves to the right of C. Both parts of that seem wrong — neither the left or right border of B should highlight when B is selected, and to drag B to the right of C you should have to drop it on the border to the right of C, not the border between B and C.

Tested in Firefox.

**Comment by flachware** [comment]
To clarify, the current implementation of the reordering of columns is just a provisional step to what we would actually like to have here (full preview of the column being dragged). But re 1, yes the 'sticky' reordering is a bug. That the target indicator does not show up for the last column has to do with 2.

Re 2, reordering to the left looks correct to me. Dragging a column slightly to the left shows the target indicator. I think it’s a good thing to show the indicator even dropping the column here does not change the order, just to have a more explicit feedback than just the cursor.

![sort-1](https://user-images.githubusercontent.com/419747/78766136-29fabc80-7989-11ea-8cc9-8fc11cfede11.png)

Once you pass the middle of the column to the left you are actually reordering and the target indicator depicts that correctly:

![sort-2](https://user-images.githubusercontent.com/419747/78766147-2cf5ad00-7989-11ea-94c6-924af0c860ea.png)

Reordering to the right does not work correctly currently, I believe that’s mainly the case because we always render the target indicator at the left side of a column, but it’s seems also to be a matter of the calculation when reordering should happen. I think we need to differentiate wether you are reordering to the left or to the right. In the latter case we have to position the target indicator at the right side of the column.

So when you drag a column slightly to the right, the target indicator would appear at the right side of that column (no reordering):

![sort-3](https://user-images.githubusercontent.com/419747/78766417-85c54580-7989-11ea-8734-cfb645b9e5ae.png)

Once you pass the middle of the column to the right, we show the indicator at the right side of that column (reordering):

![sort-4](https://user-images.githubusercontent.com/419747/78766428-88c03600-7989-11ea-8c1d-90d84595b67a.png)

**Comment by dstillman** [comment]
> I think it’s a good thing to show the indicator even dropping the column here does not change the order

I'm not sure about that — having the line appear on the left or right of the current column suggests that those are different actions, when actually neither is an action. But doesn't matter too much if this is temporary, as long as the drop behavior to the right is fixed.

**Comment by tnajdek** [comment]
I'll try to fix sticky reordering bug, that's probably regression after items table rewrite.

> The drop target behavior doesn't seem right in general...

As @flachware mentioned this is not a final implementation. Previously we've been limited by what we could do with `react-virtualized`. Recently we've switched to `react-window` which gives us more flexibility and we plan to redo the entire thing. Plan is for the entire column to move as you drag with other columns shifting to allow dragged column to take the new place (like in Tropy or Finder).

**Comment by tnajdek** [comment]
Should be slightly better in 0.12.23. I hope it's good enough for now, until we revisit this as described above, please re-open if that's not the case.

**Comment by flachware** [comment]
Looks good to me.
