### ISSUE TITLE
Columns in group library misaligned after ellipses

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#387]
In a group library, if the Title column is truncated with an ellipsis, Added By and the rest of the columns are misaligned:

![Screenshot](https://user-images.githubusercontent.com/783082/80839913-26460880-8bca-11ea-8025-3bf8ff4a666e.png)

**Comment by tnajdek** [comment]
I believe this only happens when you enable "Added by" column in a group library, then resize columns in "My Library". Resizing, reordering or selecting "restore column order" should fix this problem until next time you adjust columns while "Added by" is enabled but invisible.

Column resizing logic needs tweaks to better handle this scenario, very closely related to #360
