### ISSUE TITLE
Deleting matching item when search is active doesn't clear search

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#408]
1) Create a child note "foo bar"
2) Search for "foo bar"
3) Select the matching item and press Delete

The item row flashes, but the search isn't cleared. If you clear the search manually, the item doesn't appear in the list, because it was in fact moved to the trash, but the search should be cleared automatically if the selected item no longer matches the search.

**Comment by tnajdek** [comment]
I've recently implemented few improvements to the behaviour when searching, however scenario you've described is tricky.

Search is currently done remotely, thus we would need to re-query on every change to any of the items (or their child items) in the query. I believe this would produce laggy experience when editing an item that has been matched via search.

Alternatively, we could re-implement search logic in the web library to cover this particular case. This would be non-trivial, because child items are not fetched unless needed and we would need to account for that when doing the match.

I don't particularly like either of these solutions, any other suggestions are welcome.

**Comment by tnajdek** [comment]
On more idea: perhaps we could display an icon instead, notifying user that results might be stale due to local changes (we could also use that when remote changes are detected), and clicking it would re-query.

**Comment by dstillman** [comment]
Changes while a search is active that may or may not affect the search are a more general problem, but for this particular case couldn't we just remove the parent item from view if you 1) move it to the trash and 2) aren't in the trash?

**Comment by tnajdek** [comment]
@dstillman Simple case, where an item in results is trashed/recovered/deleted is now handled correctly, as of recent commit tagged above (1e133b58), that item will disappear from results. I've implemented that along with few other improvements in this general area.

However I thought this issue was about more complex scenario where, when a child item is triggering a match for parent item, removing it won't remove the parent item from the query results. That's still the case and I can't think of a solution other than the few I've outlined above.

**Comment by dstillman** [comment]
Oh, sorry, missed that commit.

I think I was actually just reporting the problem with deleting the parent item rather than the child item. Trying to address other changes — like deleting a matching child item — is somewhat less important, and I think one could even argue that keeping a search match in the list until the search changes, regardless of edits, is actually correct. (The client doesn't, but I'm pretty sure I've seen other apps that do, and I've occasionally noticed operations in Zotero where losing the search is a bit annoying.) So we could probably WONTFIX the rest of this. You can always click in the search box and press Return again, right?

**Comment by tnajdek** [comment]
> You can always click in the search box and press Return again, right?

Actually previously it wasn't possible to run search without changing the search input but I've changed that.

> So we could probably WONTFIX the rest of this

Agreed
