### ISSUE TITLE
Blank page with Zotero logo - npm start

### ISSUE THREAD

**Issue by olivernash** [zotero/web-library#436]
Hello - I followed the build instructions but all I am seeing when I run npm start is a blank page with the Zotero logo. Is this the expected behaviour? I'm on MacOs/ BigSur

**Comment by tnajdek** [comment]
No it's not, check the browser console for errors.

Most likely you'll see whole bunch of `403` errors. This is because you need to configure the web-library so it can access data. The easiest way to do it is to enter your user id and API key in `src/html/index.html`. You can find your user id and generate a key here: https://www.zotero.org/settings/keys
