### ISSUE TITLE
Don't allow file uploading in libraries with file editing disabled

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#505]
https://forums.zotero.org/discussion/103265/error-trying-to-add-a-pdf-file-to-a-group-in-web-library

I'm not sure what exactly we're showing now, but it seems like we're allowing people to try to upload files to libraries that don't allow file editing. We should either not allow uploading at all or show a clearer error. Not sure which is better — in the desktop app various things (e.g., dragging a file in) just don't work, and an equivalent here would be to just not have an upload button, but people do sometimes get confused in the desktop app, and there's an argument that a message would be clearer. I don't love cluttering the UI unnecessarily just to avoid occasional confusion, though, so I guess I'm inclined to try hiding it first. As long as people aren't getting an inscrutable server error that makes them think something is broken, they'd hopefully quickly notice that there are no existing files in the library…

(Could also disable the button, but that's maybe the worst option — unnecessary UI clutter without a clear explanation of why it's disabled.)

**Comment by tnajdek** [comment]
Generally speaking, we already handle this in web library, however I've missed one scenario!

This is what we do now:

1. In read-only libraries, all UI for write actions is hidden
2. In r/w libraries that don't allow files, UI for adding files is disabled
3. In both cases drag-and-drop from outside is ignored

However I think you might be right, i.e. we should be hiding UI in second case above.

And the scenario I've missed is "+" in the toolbar -> "Upload file" in r/w libraries that don't allow files. I'll hide that and also hide (instead of disabling) other parts of the UI.
