### ISSUE TITLE
Status text

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#53]
@tnajdek one thing that came to my mind when I had a look at the editable: during the update a spinner might not be the best solution everywhere – e.g. dropbox makes use of status texts when you rename a directory.

I think I would prefer the text approach to a spinner for editing small chunks of texts. So maybe we could extend our feedback repertoire?

Talking about editable, could we even have 'optimistic updates' and just let the user know if something goes wrong?

![status](https://cloud.githubusercontent.com/assets/419747/19082026/bbf4c70e-8a5c-11e6-8460-f706b78638d6.png)

**Comment by dstillman** [comment]
In this case "Renaming…" is taking the place of the entered contents? It seems weird to me to briefly get rid of what the user entered. Not sure where we'd use that.

Re: optimistic updates (which are mutually exclusive with the above, right?), they'd make for a smoother UI, but things get tricky on failure — in the item pane, what happens if the user moves on to one or more other fields and then a failure comes through? Among other things, those subsequent actions would have to be queued/batched (because the item version would change after one write, so the requests can't be sent separately, and you wouldn't want to do that for performance reasons anyway). So you'd then have multiple queued changes that might need to be rolled back, which is getting a little dangerous. We could maybe do this if we had a very short (1-second?) timeout before disabling further editing of the same item, and if all other actions (navigation, etc.) was blocked until the success response. (Would even need a warning in `onbeforeunload`.) Obviously would need to be pretty confident in the API's ability to return responses quickly before implementing this.

**Comment by dstillman** [comment]
Oh, but looking at the current Editable code, we would want to show the entered text _plus_ a spinner, not just a spinner. I'm imagining that you'd click to edit, press Enter, it would convert to the non-editable view, and there'd also be a subtle gray spinner to the right of the field.

**Comment by johanneskrtek** [comment]
Yes, the 'Renaming…' takes the place of the entered content.

It makes sense to me to show the non-editable view plus a subtle spinner, so I would go with that for now.

And yes, optimistic updates would be mutex. But actually I think the version with the text plus subtle spinner will result in a smooth looking UI, so after you mentioned some of the technical implications I am not confident anymore that it would be the right approach.

**Comment by tnajdek** [comment]
I believe this is quite outdated, we've ended up using spinner next to a field that is being processed and I think it works quite well. Feel free to re-open if needed.
