### ISSUE TITLE
Special collections

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#72]
Currently the navigation just renders collections, but we are missing 'special collections' like 'All Documents', 'My Publications', 'Duplicate Items', 'Unfiled Items' and 'Trash'. Also the 'Add collection' item.

For some of those we might want the possibility to have an icon different to the regular collections, as it can be seen in the draft:

![my-library](https://cloud.githubusercontent.com/assets/419747/23158453/8d1c425a-f81f-11e6-840d-5a7df21f9696.png)

**Comment by tnajdek** [comment]
I doubt we will implement 'Duplicate Items' and 'Unfiled Items' and we've decided not to use 'Add collection' because it would force user to scroll down to the bottom to add a new collection. 

I believe the only one missing at this point is 'My Publications', for which we can probably have read-only support.

**Comment by dstillman** [comment]
We probably should support Unfiled Items — people do rely on that pretty heavily. But it'll need API support, either as its own thing (which would be easy) or as an advanced search (which would be hard), so not something we can do at the moment.

**Comment by tnajdek** [comment]
The two remaining "special" collections are 'Duplicate Items' and 'Unfiled Items'. Since support for these cannot be easily added and would require API changes, I'd argue this is not a 1.0 thing. We can revisit in the future: #146
