### ISSUE TITLE
Editable

### ISSUE THREAD

**Issue by johanneskrtek** [zotero/web-library#84]
<img width="792" alt="editable-1 0" src="https://cloud.githubusercontent.com/assets/419747/24809396/a9951c68-1bbf-11e7-9bcb-fd70f64c4951.png">

@tnajdek here is a quick study in regard to the editable component (left column = desktop, right column = phone). There are some details that can be seen from the mockup that might need adjustments in the current editable:

1. On the desktop: in order to provide a more stable experience after entering a value, the value and the spinner should be visible at the same time.

1. On the phone: when editing a field the whole line should be highlighted, that means the `dt` must also be aware of the editable state. On a related note – if the `dl` causes any problems (as related `dt` and `dd` do not have a common root element), let’s switch to a regular `ul` and nest another `ul` with two `li` (or just use two `div` inside), it’s not worth it.

1. On mobiles we do not show the spinner for each editable but just one global. I think I can show and hide the editable spinner with CSS, so there is no need for viewport specific JavaScript (but we need two spinners). 

1. Do we actually need the `<form>` element around the form control?

**Comment by johanneskrtek** [comment]
@tnajdek I added some basic desktop styles to keep the text position stable during the editable switches. So when you click on an editable field to activate it, there should be no jump.

For the next step I would need the spinner and the `div.editable` (formerly `span.editable`) in place at the same time. After that I will have a look at the mobile version.

the `<form>` element has no side effects so far, but if you do not absolutely need it, I would suggest to drop it.

**Comment by johanneskrtek** [comment]
@tnajdek related to the editable: it would be handy if a power user could tab directly to the next editable from a currently active editable input field. would it be possible to **not** set the `.keyboard` class in this case? otherwise the power user would end up with focus states all over the interface, while those states are intended for handicapped persons, not for power users.

**Comment by tnajdek** [comment]
Hey @johanneskrtek 

Design suggestion/study looks great, let's make it happen :) Also thanks for all the suggestions, here are some answers (I've edited your first post to use numeric list):

1. That's done. Spinner needs some styling tweak
2. Both `dt` and `dd` now receive class `editing`. Happy to change the name to be more specific if needed
3. I've added spinner in `details.jsx` and wrapped it with a `div.hidden-sm-up`. Feel free to re-arrange this in any way you need. If it needs to live in other component - let me know.
4. Nope, `<form>` is gone now

> Currently a lot of fields get displayed – could you restrict the fields to those that actually belong to the current item type?

Yes, this will be done at some point.

> it would be handy if a power user could tab directly to the next editable from a currently active editable input field

That would be handy, I'll look into it - it might be a candidate for a separate issue

**Comment by johanneskrtek** [comment]
Hi @tnajdek 

Re 1: Ok, it took me a while to get the editable layout right – CSS truncation and flex can be a headache. The other thing is precise vertical alignment of text for different fonts across all browsers. But give it a try – it should be completely stable now. Please let me know if it isn’t … (fingers crossed)

Re 4: Cool, but I think we lost the ability to confirm a change with the return key now?

I can still reproduce endless spinners when I leave an editable (click outside) without changing the value.

**Comment by tnajdek** [comment]
> Re 4: Cool, but I think we lost the ability to confirm a change with the return key now?

Yeah, I'll fix that

> I can still reproduce endless spinners when I leave an editable (click outside) without changing the value.

I've updated the minimum required libzotero version in package.json so `npm i` should fix this.

**Comment by johanneskrtek** [comment]
@tnajdek I added a button in `touch-header.jsx` in line 105 that should toggle a new class `editing` on `<ItemDetails/>`. This will be needed to switch between default and edit mode on phones.

The spinner you added to `details.jsx` needs to live in `touch-header.jsx` – right before the button.

**Comment by johanneskrtek** [comment]
@tnajdek I reached the conclusion that we will breakpoint specific JavaScript: for mouse devices you can simple click an editable to edit its content, but on touch devices you have to activate 'edit mode' first. Which means we have to actively allow or disallow activating editables on click.

So, what is a touch device? We linked touch devices to 2 factors: to the touch mode (which is no problem to identify as you set the class yourself) and the viewport width – currently every viewport width smaller than `992px` is a tablet or phone. 

Hence I think we need breakpoint specific behavior. Note that the CSS breakpoints test the viewport width, not the device width (that’s the way Bootstrap does it). That means even resize has to be taken in account in JS.

I tested device width specific media queries in the styles for a short time – but mixing those with viewport width media queries makes the whole thing really complicated, there are simply too many combinations then, so I would be happy to stick to the viewport width for media queries.

**Comment by johanneskrtek** [comment]
Fyi, I will replace the `dl` with an `ol`, styles already got hacky – this was the last time a gave `dl` a try at all.

**Comment by tnajdek** [comment]
@johanneskrtek I need some clarification on **Save** and **Cancel** buttons.

1. Do we want to held off sending changes to the server until **Save** is pressed?
1. Should **Cancel** revert all changes done to the object so far (since pressing **Edit**)?
1. Should navigating away from this view trigger **Cancel**?
1. Do we want a different mechanism on mobile and desktop?

Currently all changes are transmitted to the server immediately once the editable field looses focus. If all above is true, that adds substantial complexity as we will need to handle both cases (locally cached changes vs. immediately updated objects). If possible, I'd rather avoid having that.

**Comment by dstillman** [comment]
If we actually had Save and Cancel buttons, I think the answer to 1, 2, and 4 would be yes, and for 3 we'd prompt whether to leave without saving.

But I'm not sure there's any reason not to just have the opposite of "Edit" be "Done". Edit would turn the fields into textboxes but otherwise they'd behave exactly like they do on desktop without the Edit button, and Done would simply turn them back to labels (but they'd already be saved). There'd be the same sort of spinner/checkmark next to each edited textbox that we'd show in click-to-edit mode on the desktop — the textbox just wouldn't automatically convert back to a label afterward.

I also wonder if we should support tap-to-edit for individual fields on mobile, with the Edit button there just for discoverability of the edit mode, but that might be too complicated or lead to accidental mode toggles.

**Comment by tnajdek** [comment]
I'd prefer @dstillman's approach of having Edit -> Done on mobiles with fields saved on blur (as on desktop version). From the implementations standpoint it's less complex. What do you think @johanneskrtek?

**Comment by johanneskrtek** [comment]
@tnajdek I’m fine with @dstillman’s approach.

The only drawback i see, is, that **Cancel** had kind of an undo function. But I guess we won’t have undo in the desktop version of the web library neither, right?

Please note that it is very likely that there is an active (not blurred) editable left when you tap **Done**. In this case we switch the layout back to default and show the spinner as long this item saves?

Now without the **Cancel** button navigating away should probably also save?

Would look like this:

<img width="792" alt="editable-1 1" src="https://cloud.githubusercontent.com/assets/419747/25533279/6873dd38-2c30-11e7-8d3f-f2028220a7e6.png">

**Comment by tnajdek** [comment]
Relevant commit: 4918787218db94455320d624f176c4644450e9d7

**Comment by tnajdek** [comment]
This is now done, matching the above, updated design on desktop and mobile. Also all functionality mentioned in comments should be implemented now, except for the following:

* It's not yet possible to enable edit-mode on tablets #88
* All fields are displayed, instead of showing only item type specific fields #89

@johanneskrtek if I missed anything, please feel free to re-open.

**Comment by johanneskrtek** [comment]
@tnajdek looks good to me.
